name: CI phpunit

on:
  push:
    branches:
      - master

jobs:
  phpstan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - "8.1"

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPStan
        uses: php-actions/phpstan@master
        with:
          path: src/
          version: "1.1"
          level: 9
          php_version: ${{ matrix.php }}

  build-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1, 8.2]

    steps:
      - uses: actions/checkout@v3

      - uses: php-actions/composer@v6

      - name: PHPUnit Tests
        uses: php-actions/phpunit@master
        with:
          version: "9.5"
          bootstrap: vendor/autoload.php
          configuration: phpunit.xml.dist
          php_version: ${{ matrix.php }}
